[ms]
  languageName = "Rumi"
  contentDir = "content/rumi"
  weight = 10
  [ms.params]
    languageISO = "MY"


[ms-arab]
  languageName = "جاوي"
  contentDir = "content/jawi"
  languagedirection = 'rtl'
  weight = 15
  [ms-arab.params]
    languageISO = "JW"
    title = "ڤدومن شيرايوکي"
    titleAddition = "سومبر روجوعن اندا!"
    titleHome = "ڤدومن شيرايوکي"
    footer = "دکواساکن اوليه <a class=\"text-muted\" href=\"https://gohugo.io/\">هوݢَو</a> دان <a class=\"text-muted\" href=\"https://getdoks.org/\">دَوک‌س</a>"
    alertText = "<span dir='rtl'>ماسيه ددالم ڤمبيکينن يڠ امت ڤرلاهن<br>تاتالتق کانن ککيري ماسيه بلوم سمڤورنا</span>"
