# Meta Data for SEO

## Homepage
title = "Rujukan Syirayuki"
titleSeparator = "-"
titleAddition = "Sumber Rujukan Anda!"
description = "Terjemahan dan catatan B.Melayu Rumi/Jawi bagi pelbagai bahan rujukan maya."

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["doks.png"]
ogLocale = "ms-MY"
domainTLD = "github.io"
titleHome = "Rujukan Syirayuki"

## Twitter Cards
twitterSite = "#"
twitterCreator = "@niskala5570"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Rujukan Syirayuki"
schemaAuthor = "Niskala5570"
schemaAuthorTwitter = "https://twitter.com/niskala5570"
schemaAuthorLinkedIn = "#"
schemaAuthorGitHub = "https://github.com/niskala5570"
schemaLocale = "ms-MY"
schemaLogo = "logo-doks.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "doks.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/getdoks"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/h-enk/doks"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [1920, 900, 800, 700, 600, 500]
portraitPhotoWidths = [1200, 800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "2000"

# Footer
footer = "Dikuasakan oleh Github, <a class=\"text-muted\" href=\"https://gohugo.io/\">Hugo</a> dan <a class=\"text-muted\" href=\"https://getdoks.org/\">Doks</a>"

# Feed
copyRight = "Hak Cipta (c) 2021-2022 Projek Syirayuki"

# Alert
alert = true
alertDismissable = true
# alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
alertText = "Masih dalam pembikinan yang amat perlahan"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
#repoHost = "Gitea"
docsRepo = "https://github.com/projeksyirayuki/rujukan"
docsRepoBranch = "master"
docsRepoSubPath = ""
editPage = false
lastMod = false

[sections]
  sectionNav = ["aegisub"]

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  multilingualMode = true
  docsVersioning = false
  fullWidth = true
  navbarSticky = true

[menu]
  [menu.section]
    auto = false
    collapsibleSidebar = true
